includes/gateways/adspanel.class.php
includes/gateways/avalpayam.class.php
includes/gateways/bandarsms.class.php
includes/gateways/idehpayam.class.php
includes/gateways/joghataysms.class.php
includes/gateways/mdpanel.class.php
includes/gateways/mediana.class.php
includes/gateways/mydnspanel.class.php
includes/gateways/nasrpayam.class.php
includes/gateways/payamakalmas.class.php
includes/gateways/ponishasms.class.php
includes/gateways/sadat24.class.php
includes/gateways/smsde.class.php
includes/gateways/smshooshmand.class.php
includes/gateways/smsmaster.class.php
includes/gateways/smsmelli.class.php
includes/gateways/smsservice.class.php
includes/gateways/yashilsms.class.php

Seems like someone forget to change this path. 🤔

fixed path to the nusoap class on some gateways

---

includes/class-wp-sms-gateway.php
includes/gateways/gatewayapi.class.php

The GatewayAPI.com SMS-gateway included in WP-SMS.

Add Gatewayapi.com integration

---

includes/class-wp-sms-gateway.php
includes/gateways/_ebulksms.class.php
includes/gateways/includes/ebulksms/ebulksms.class.php
includes/templates/send/send-sms.php

Hi Mostafa,
I just saw your SMS plugin and I think it's a really great code you've written. 
I noticed there was only one gateway available for Africa and EbulkSMS wasn't included.
So I've just written some code for this and made a slight improvement to the UI for the "Send SMS" template.
Would be great if you merge these into your master branch.
Many thanks.

EbulkSMS Africa Gateway

---

includes/class-wp-sms-gateway.php
includes/gateways/mobtexting.class.php

adding one of the provider available in India to this.
Mobtexting Support sending SMS to Indian Mobile Numbers. If Someone having account in mobtexting he can use this plugin using username and api key.

Gateway Mobtexting Addition for India

---

includes/gateways/smshosting.class.php

Fix for the accents bug on SMSHosting messages.

SMSHosting Encoding Fix

---

includes/class-wp-sms-gateway.php
includes/gateways/engy.class.php

Included the https://www.engy.solutions/ gateway. Please review it and let me know if it's suitable to be included in the next update. Thanks!

Added Engy Solutions Gateway

---

.gitignore
includes/gateways/_ebulksms.class.php
includes/templates/send/send-sms.php
wp-sms.php

Allow typing of sender ID in Admin Send SMS page

---

includes/class-wp-sms-gateway.php
includes/gateways/jusibe.class.php

I will like to add https://jusibe.com gateway to WP SMS.
Thanks.

Add Jusibe.com gateway

---

includes/gateways/comilio.class.php

The new default message type for Comilio platform is "SmartPro"

Updated message type for gateway Comilio

---

includes/gateways/class-wpsms-gateway-smsgatewaycenter.php

Added and validated as per JSON response.

Updated New API for Sms Gateway Center

---

includes/gateways/class-wpsms-gateway-mtarget.php

- Move to more recent URL
- Add a proper way to check credit
- Send one request per 500 numbers, instead of one request per number

Update MTarget's gateway

---

.gitignore
includes/gateways/class-wpsms-gateway-abrestan.php
includes/gateways/class-wpsms-gateway-joghataysms.php
includes/gateways/class-wpsms-gateway-mdpanel.php
includes/gateways/class-wpsms-gateway-mediana.php
includes/gateways/class-wpsms-gateway-nasrpayam.php
includes/gateways/class-wpsms-gateway-smsde.php
includes/gateways/class-wpsms-gateway-yashilsms.php

Dear Contributors,
According to our last movement for our datacenter
all if old IPs have been changed, so please accept this pull request in order that other companies be able to continue their businesses

Correct IPs cause datacenter has changed

---

includes/gateways/class-wpsms-gateway-smsmelli.php

update wsdl link

---

includes/gateways/class-wpsms-gateway-melipayamak.php

melipayamak shared service is added along side the normal send function using the dedicated line.
in this case melipaymak users can send their messages to block numbers using baseservice

class-wpsms-gateway-melipayamak updated

---

includes/class-wpsms-rest-api.php

Revert "welcome-message-fixed"

---

includes/class-wpsms-notifications.php

fixing boolean logic issue

---

includes/gateways/class-wpsms-gateway-bulkgate.php

Hello,
I just added application_productparameter for better identification your plugin in our portal (history, inbox etc.). We will use your logo insted of default logo for api.

BulkGate application_product parameter 2

---

includes/class-wpsms.php
src/Helper.php
src/User/RegisterUserViaPhone.php
src/User/UserHelper.php
src/User/UserLoginHandler.php

...
[Asana Card](https://app.asana.com/0/1198506570108127/1208339223299227/f) 
- …

Implement new username format

---

src/User/MobileFieldHandler/WooCommerceAddMobileFieldHandler.php
src/User/MobileFieldHandler/WooCommerceUsePhoneFieldHandler.php

Fix error on user creation in admin -> users.
-   [X] Fix - Fixes an existing bug
-   [X] Dev - Development related task …

Fix error on user creation in admin -> users

---

includes/class-wpsms.php
src/Components/NumberParser.php
src/Helper.php
src/User/MobileFieldHandler/WooCommerceAddMobileFieldHandler.php
tests/wpunit/NumberParserTest.php

Implement number parser

---

includes/admin/settings/class-wpsms-settings.php

Update checkbox field description for ultimate member integration
https://app.asana.com/0/1198989906204083/1208311550998513/f
-   [ …

Fix: Update checkbox field description for ultimate member integration

---

src/SmsOtp/Generator.php
src/SmsOtp/SmsOtp.php
src/SmsOtp/Verifier.php

...
-   [x] Update - Update existing functionality
-   [ ] Enhancement - …

Support filters for rate limiter

---

includes/admin/settings/class-wpsms-settings.php

Add documentation URL for Ultimate Member under integrations tab
-   [ ] …

Add documentation URL for Ultimate Member under integrations tab

---

readme.txt
src/Widget/AbstractWidget.php
src/Widget/Widgets/StatsWidget.php

- Add Capability condition to widget. …

Add capability check to widgets

---

.gitignore

Update .gitignore file based on phpunit
-   [] Fix - Fixes an existing bug …

update .gitignore based on phpunit

---

CHANGELOG.md
includes/class-wpsms-gateway.php
includes/gateways/class-wpsms-gateway-mobilemessage.php

Adding Mobile Message Gateway to WP SMS
Task: https://app.asana.com/0/1208253022496699/1209156677676033/f
-   [ ] Tweak - A minor …

feat: add mobilemessage (australia) gateway

---

CHANGELOG.md
includes/admin/class-wpsms-version.php

Prioritizing free gateways above pro gateways.
https://app.asana.com/0/1198506570108127/1209187975908060/f 
-   [ ] Tweak - A minor …

Reorder gateways list

---

CHANGELOG.md
includes/class-wpsms-gateway.php
includes/gateways/class-wpsms-gateway-hellosms.php

Adding HelloSMS gateway (Sweden)
https://app.asana.com/0/1208253022496699/1209187975908069/f
-   [ ] Tweak - A minor adjustment to …

feat: add hellosms.se gateway

---

includes/admin/class-wpsms-version.php
includes/class-wpsms.php
src/Admin/LicenseManagement/LicenseMigration.php
src/Services/Hooks/HooksManager.php
src/Utils/PluginHelper.php

merging changes to main dev breanch …

Update license manager

---

CHANGELOG.md
src/Notification/Handler/WooCommerceOrderNotification.php

Support variable products in order to get its meta
-   [x] Update - Update existing functionality …

feat: support variable products meta

---

readme.txt
src/Services/Subscriber/SubscriberUtil.php

Fix subscription activation issue …

fix subscription mobile activation issue

---

includes/class-wpsms-gateway.php

Matinsms class adresses changed …

Changing Matinsms class addresses

---

includes/class-wpsms-newsletter.php
src/Controller/PublicUnsubscribeAjax.php

fix unsubscribe issue

---

CHANGELOG.md
includes/templates/admin/send-sms.php

Correct typo in sens-sms.php line 259 and ensure the string is translatable for Loco Translate.
-   [ ] Tweak - A minor adjustment …

fix: correct typo in send-sms.php

---

CHANGELOG.md
readme.txt
src/User/MobileFieldHandler/WooCommerceAddMobileFieldHandler.php

Fix disappearing billing fields …

fix disappearing billing fields

---

src/Notification/Handler/WooCommerceOrderNotification.php
src/Notification/Notification.php

Handling meta and item meta in the notification …

Handling meta and item meta in the notification

---

includes/class-wpsms-newsletter.php

fix unsubscription wrong response condition …

fix unsubscription wrong response condition

---

CHANGELOG.md
readme.txt
src/Notification/Notification.php

Fix the argument replacement issue in sending notifications by removing extra conditions.
-   [ ] Tweak - A minor adjustment to …

fix argument replacement issue in sending notifications

---

CHANGELOG.md
src/Admin/LicenseManagement/Abstracts/BasePage.php

Fix the screen options disappearing on other pages.
-   [ ] Performance - …

Add condition to target only plugin pages

---

CHANGELOG.md
src/Admin/AjaxOptionUpdater.php
src/Admin/LicenseManagement/Plugin/PluginActions.php
src/Controller/LicenseManagerAjax.php

Checking user capabilities to see if they are allowed to update options, install, and activate plugins.
-   [ ] Tweak - A minor …

Release 7.x fix ajax option restriction

---

CHANGELOG.md
includes/class-wpsms-notifications.php

Send post publish SMS only for selected taxonomy term IDs (notif_publish_new_taxonomy_and_term)
-   [ ] Tweak - A minor adjustment …

Send post publish SMS only for selected taxonomy term IDs (notif_publish_new_taxonomy_and_term)

---

CHANGELOG.md
includes/admin/outbox/class-wpsms-outbox.php
includes/class-wpsms.php
src/Components/Logger.php
src/Services/Database/Migrations/SchemaMigration.php
src/Services/Email/EmailLogger.php
src/Services/Email/EmailResult.php
src/Services/Email/EmailService.php
src/Settings/Abstracts/AbstractSettingGroup.php
src/Settings/Groups/EmailSettings.php
src/Settings/SchemaRegistry.php
tests/unit/EmailServiceTest.php

Implement email delivery system …

Release 7.3 email delivery system

---

CHANGELOG.md
includes/class-wpsms-gateway.php

Support SMSALA gateway
-   [ ] …

feat: add smsala to the list

---

CHANGELOG.md
includes/gateways/class-wpsms-gateway-sms.php

Added support for Service-Line SMS.ir template-based messaging.
-   [x] Update - Update existing functionality
-   [ ] …

feat(sms-ir): add template-based messaging support

---

frontend/.prettierignore
frontend/src/components/form/field-renderer.tsx
frontend/src/components/form/fields/checkbox-field.tsx
frontend/src/components/form/fields/color-field.tsx
frontend/src/components/form/fields/multiselect-field.tsx
frontend/src/components/form/fields/number-field.tsx
frontend/src/components/form/fields/text-field.tsx
frontend/src/components/form/fields/textarea-field.tsx
frontend/src/components/form/fields/url-field.tsx
frontend/src/components/form/form-actions.tsx
frontend/src/components/form/schema-form.tsx
frontend/src/components/ui/tabs.tsx
frontend/src/globals.css
frontend/src/hooks/use-form.tsx
frontend/src/routes/otp/_layout.tsx
frontend/src/routes/otp/_layout/authentication-channels.tsx
frontend/src/routes/otp/_layout/branding.tsx
frontend/src/types/general.d.ts
frontend/src/types/settings/group-schema.d.ts
src/Admin/Pages/SettingAdminPage.php

OTP branding page
-   [*] Fix - Fixes an existing bug
-   [*] Add - Adds functionality
-   [ ] …

Release 7.3 otp mfa branding page

---

frontend/src/app.tsx
frontend/src/components/form/field-wrapper.tsx
frontend/src/components/form/fields/select-field.tsx
frontend/src/components/header.tsx
frontend/src/components/ui/combobox.tsx
frontend/src/routes/settings/_layout.$name.tsx
frontend/src/types/settings/group-schema.d.ts

save with add-on payload - fix some reported bugs
-   [*] Fix - Fixes an existing bug
-   [*] Add - Adds functionality …

feat: include addon with save payload
